apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-service-config
  namespace: lojaveloz
data:
  SPRING_PROFILES_ACTIVE: production
  SERVER_PORT: "8083"
  DB_URL: jdbc:postgresql://postgres-svc:5432/stock
  DB_USER: lojaveloz
  RABBITMQ_HOST: rabbitmq-svc
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: lojaveloz
  OTEL_SERVICE_NAME: stock-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector-svc:4317
  LOG_LEVEL: info
  TZ: America/Sao_Paulo
