apiVersion: v1
kind: Service
metadata:
  name: stock-service-svc
  namespace: lojaveloz
  labels:
    app: stock-service
spec:
  selector:
    app: stock-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
