# Mesmo padrão do order-service.
# Aplicar manualmente em dev:
#   kubectl create secret generic payment-service-secrets \
#     --from-literal=db-password='SUA_SENHA' \
#     --from-literal=rabbitmq-password='SUA_SENHA' \
#     -n lojaveloz
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-service-secrets
  namespace: lojaveloz
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: payment-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: lojaveloz/payment-service
        property: db_password
    - secretKey: rabbitmq-password
      remoteRef:
        key: lojaveloz/payment-service
        property: rabbitmq_password
